function seg = svg_bezier_parser(str)
% Limited functionality - No sanity checks - only for internal use.
% parses relative svg paths generated by Inkscape

str = char(str);
idx = 1;
is_abs = true;
if str(1) == 'm'
    is_abs = false;
end

idx = idx + 2;
str = str(idx:end);


S = [0;0];
idx_end = find(str == ',',1) - 1;
S(1) = str2double(str(1:idx_end));
idx = idx_end + 2;
str = str(idx:end);

idx_end = find(str == ' ',1) - 1;
S(2) = str2double(str(1:idx_end));
idx = idx_end + 2;
str = str(idx:end);

% pass 'c' char
str = str(3:end);

i = 1;
j = 1;
tMat = S;
flag = true;
while flag
    idx_end = find(str == ',',1) - 1;
    S(1) = str2double(str(1:idx_end));
    idx = idx_end + 2;
    str = str(idx:end);

    idx_end = find(str == ' ',1) - 1;
    if isempty(idx_end)
        % end of data is reached
        S(2) = str2double(str(1:end));
        flag = false;
    else
        S(2) = str2double(str(1:idx_end));
        idx = idx_end + 2;
        str = str(idx:end);
    end


    j = j + 1;

    if ~is_abs
        % tMat(:,1) is considered to be the reference point
        tMat(:,j) = S + tMat(:,1);
    else
        tMat(:,j) = S;
    end

    if j == 4
        seg{i} = tMat;

        i = i + 1;
        j = 1;
        tMat = [tMat(:,4), zeros(2,3)];
    end

end




end
